### ISSUE TITLE
Lint系ツールの追加

### ISSUE THREAD

**Issue by hppRC** [nama-tamago/p1ass-lt-site#6]
![image](https://user-images.githubusercontent.com/48990104/97772347-7c9c0000-1b89-11eb-8fdb-77747bcfd38b.png)

**Comment by uzimaru0000** [comment]
僕は平和主義なので皆さんに合わせます

**Comment by saitolume** [comment]
typescript-eslint と prettier を使うなら細かいルールはこだわらないです

**Comment by hppRC** [comment]
こだわりないです
